#!/usr/bin/env python3

import argparse
import pexpect
import time
import sys
import configparser
import os
import syslog
import datetime
import atexit

ip="127.0.0.1"
Debug = 0
name = __file__
#----                                                                                                        
# Read the command line for the arguments
#                                                                                                         
def ParseArgs():
    """Parse the command line arguments."""

    parser = argparse.ArgumentParser(description="Zeroize Juniper EX.")

    parser.add_argument("--port", '-p', type=int, help="Specifiy the port to monitor")
    parser.add_argument('--user', '-u')    
    parser.add_argument('--password', '-w')
    parser.add_argument('--logfile', '-l')    
    parser.add_argument('--debug', '-d', action='store_true')    
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--zero', '-z', action='store_true')
    group.add_argument('--reboot', '-r', action='store_true')
    args = parser.parse_args()

    return(args)

#
# ParseConfigFile
#
def ParseConfigFile(file):

    parser = configparser.ConfigParser()

    try:
        with open(file) as f:
            parser.read(file)
    except IOError:
        print(f"Can't read config file {file}")
        syslog.syslog(f"Can't open config file:{file}. Aborting!")        
        exit()
        
    cz = parser['cz']

    port = cz['port']
    user = cz['user']
    password = cz['password']
    Debug = cz['debug']
    zero = cz['zero']
    reboot = cz['reboot']
    logfile = cz['logfile']

    args = ParseArgs()

    if args.port:
        port = args.port
    if args.debug != False:
        Debug = args.debug
    if args.user != None:
        user = args.user
    if args.password != None:
        password = args.password
    if args.reboot != False:
        reboot = args.reboot
    if args.zero != False:
        zero = args.zero
    if args.logfile != None:
        logfile = args.logfile

    return(port, Debug, user, password, reboot, zero, logfile)

#
# OpenLog
#
def OpenLog(file):

#    if os.path.isfile(file):
#        os.rename(file, file+".old")
    try:
        f = open(file, 'w')
    except:
        syslog.syslog(f"Can't open {file}. Aborting!")
    f.write('\n')
    f.write(f'{datetime.datetime.now()} [{os.getpid()}] Start logging for Chassis Zeroize')
    f.write('\n')
    f.flush()
    return(f)
#
# Log
#
def Log(flag, msg):
    global Debug

    if Debug or flag:
        lf.write(f'{datetime.datetime.now()} [{os.getpid()}] {msg}\n')
        lf.flush()
#
# PidFile
#
def PidFile():
    global name
    try:
        pid = os.getpid()
    except:
        syslog.syslog('Failed to get PID!')
        exit()

    name = os.path.basename(__file__)
    try:
        f = open(f'/run/{name}.pid', 'w')
    except:
        syslog.syslog('Failed to open PID file!')
        exit()
    f.write(str(pid))
    atexit.register(TidyUp)
    f.close()

#
# Tidy Up
#
def TidyUp():
    global name
#    name = os.path.basename(__file__)
    file = f'/run/{name}.pid'
    Log(1, 'Removing PID file.')
    if os.path.exists(file):
        os.remove(file)
    else:
        Log(1, 'Error: PID file not found')
#
# Reboot
#
def Reboot():
    Log( 0,'In Reboot...')

    conn.sendline('request system reboot')

    i = conn.expect(['the system ? ', pexpect.TIMEOUT], timeout=3)    

    if i == 1:
        Log( 0,'Unexpected timeout waiting for reboot acknowledgement.')
        Log( 0,str(conn))
    else:
        Log( 0,'Yes to reboot')
        conn.sendline('y')
        
    while True:
        time.sleep(15)
        i = conn.expect(['login: ', pexpect.TIMEOUT], timeout=15)
        if (i == 1):
            Log( 0,'Still waiting for reboot to finish.')
        else:
            break

    Log( 0,'Finished reboot!')

#
# Zeroize
#
def Zeroize():
    Log( 0,'In Zeroize...')
#    exit()
    time.sleep(15)
    return()
    conn.sendline('request system zeroize')

#    i = conn.expect(['will be zeroized ', pexpect.TIMEOUT], timeout=3)
    i = conn.expect(['including configuration and log files', pexpect.TIMEOUT], timeout=3)        

    if i == 1:
        Log( 0,'Unexpected timeout waiting for reboot acknowledgement.')
        Log( 0,str(conn))
        return
    else:
        Log( 0,'Yes to zeroize')
        conn.sendline('y')
        
    while True:
        time.sleep(15)
        i = conn.expect(['localhost login: ','login: ', pexpect.TIMEOUT], timeout=30)
        if (i == 0):
            Log( 0,'Got WRL login')
        elif (i == 2):
            Log( 0,'Still waiting for zeroize to finish.')
        else:
            break

    Log( 0,'Finished zeroize!')

    conn.sendline('root')
    i = conn.expect(['root@.*% ', pexpect.TIMEOUT], timeout=60)
    if (i == 1):
        Log( 0,'Timeout waiting for prompt after Zeroizing.')
        return
        Log( 0,'cli')

    conn.sendline('cli')
    time.sleep(5)

    i = conn.expect(['root> ', pexpect.TIMEOUT], timeout=30)
    if (i == 1):
        Log( 1,'Timeout waiting for CLI prompt after Zeroizing.')
        return
    Log( 0,'request power off')
    conn.sendline('request system power-off')
    time.sleep(1)
    i = conn.expect(['Power Off the system ', pexpect.TIMEOUT], timeout=15)
    if ( i == 1 ):
        Log( 0,'Timeout waiting for "Power Off the system"')
        return
    Log( 0,'send yes')
    conn.sendline('yes')
    time.sleep(30)
    return
#
# Login
#
def Login():
    Log( 0,'In login...')

    conn.sendline(f'{user}')
    Log( 0,f'Sent {user}, now send Password {password}...')

    i = conn.expect(['[Pp]assword:', 'root@:.+%', pexpect.TIMEOUT], timeout=60)    

    if i == 0:
        Log( 0,f'Sending {password}')
        conn.sendline(f'{password}')
    elif i == 1:
        Log( 1,'Send cli')
        conn.sendline('cli')

    elif i == 2:
        Log( 1,'Timeout in Login')
#        exit()
        return()        
    Log( 0,'Look for prompt')

    i = conn.expect(['Login incorrect', pexpect.TIMEOUT, f'{user}@', f'{user}>' ], timeout=60)

    if i == 0:
        Log( 1,f'Password does not work!')
#        exit()
        return()        
    elif i == 1:
        Log( 1,f'Timed out waiting for prompt.')
#        exit()
        return()        
    elif i == 2:
        Log( 1,'Logged in...')
    return


#
# Main
#

if __name__ == "__main__":

    syslog.syslog('Starting cz...')
#    (port, debug, user, password, reboot, zero, logfile) = ParseConfigFile('./cz.conf')
    (port, debug, user, password, reboot, zero, logfile) = ParseConfigFile('/etc/cz.conf')    

    lf = OpenLog(logfile)

    if debug == "False":
        Debug = 0
    else:
        Debug = 1

    Log( 0,f'Port: {port}')
    Log( 0,f'User: {user}')
    Log( 0,f'Passwd: {password}')
    Log( 0,f'Debug: {Debug}')
    Log( 0,f'Zero: {zero}')
    Log( 0,f'Reboot: {reboot}')

    PidFile()
#    exit()
    
    conn = pexpect.spawn(f"telnet {ip} {port}")

#    if Debug:
#        Log( 0,'Turn on logging...')
#        conn.logfile = sys.stdout.buffer
        
    while True:
        Log( 0,'Looping...')
        conn.sendline()

        i = conn.expect(['Amnesiac', 'Last login: ', 'login: ', 'Port already in use', f'{user}.*> ',
                         f'{user}.*# ', f'{user}.*%', pexpect.EOF, pexpect.TIMEOUT], timeout=3)    
        if i == 0:
            Log( 0,'Got Amnesiac')
            i = conn.expect(['login: ', f'{user}.*> ', f'{user}.*# ', f'{user}.*%',
                             pexpect.EOF, pexpect.TIMEOUT], timeout=3)
            if ((i == 4) or ( i == 5)):
                Log( 0,'Error after Amnesiac prompt!')
            time.sleep(5)
            
        if i == 1:
            Log( 0,'Got Banner')
                  
        elif i == 2:
            Log( 0,'Got login: ')
            Login()
        
        elif i == 3:
            Log( 0,'Got Port in use ')
            conn.close()
            time.sleep(5)
            conn = pexpect.spawn(f"telnet {ip} {port}")
            
        elif i == 4:
            Log( 0,'Got prompt. ')
            if (reboot == True):
                Reboot()
            else:
                Zeroize()

            Log( 0,'Going to break now')
            break

        elif i == 5:
            Log( 0,'Got config prompt')
            conn.sendline('exit')
            
        elif i == 6:
            Log( 0,'Got Shell')
            conn.sendline('cli')

        elif i == 7:
            Log( 1,'Got EOF ')            

        elif i == 8:
            Log( 1,'Timeout!')
            conn.sendline()

#    Log( 0,str(conn))
    conn.kill(0)        
